from turtle import*
#due want to paint a house

#«step 1:
width(7)
color ("purple")
forward (200)
left (90)




#draw a square
forward (200)
left (90)
forward (200)
left (90)
forward (200)
left(90)
 

 
 
 # end of squre





#drawing a door
forward (70)
color ("yelow")
left (90)
forward(120) #height of the door right (90)
forward (60)
right (90)
forward (120)
penup()
goto (200, 200) (pendown)
color ("red")
right (150)
forward("20ep")
exitonclick()
